name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: './'

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
  
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1883:1883 8883:8883 1891:1891'
          config: ${{ github.workspace }}/.github/workflows/mosquitto.conf
          container-name: 'mqtt'

      - name: Download go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Get dependencies
        run: go mod tidy   
      - name: Test
        run: go test -v --cover .
